"use client";
import { usePathname } from "next/navigation";
import Link from "next/link";
import { Asterisk, ArrowUpRight, Menu } from "lucide-react";
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription, SheetClose } from "@/components/ui/sheet";
const links=[['Services','/services'],['Work','/work'],['About','/about']];
export function Brand(){return <Link href="/" className="brand" aria-label="AsterSync home"><Asterisk aria-hidden="true"/>AsterSync<span className="brand-period">.</span></Link>}
export function Header(){const path=usePathname();return <header className="site-header"><div className="wrap nav-inner"><Brand/><nav className="nav-links" aria-label="Main navigation">{links.map(([label,url])=><a key={url} href={url} aria-current={path===url?'page':undefined}>{label}</a>)}</nav><a href="/contact" className="nav-contact">Let’s talk <ArrowUpRight size={16}/></a><Sheet><SheetTrigger asChild><button className="mobile-toggle" aria-label="Open menu"><Menu size={25}/></button></SheetTrigger><SheetContent><div className="mobile-nav"><SheetTitle>AsterSync</SheetTitle><SheetDescription>Explore the studio.</SheetDescription>{[['Home','/'],...links,['Contact','/contact']].map(([label,url])=><SheetClose asChild key={url}><a href={url} aria-current={path===url?'page':undefined}>{label}</a></SheetClose>)}</div></SheetContent></Sheet></div></header>}
export function Footer(){return <footer className="site-footer"><div className="wrap"><div className="footer-main"><div><Brand/><p>Thoughtful software.<br/>Connected systems. Simpler work.</p></div><nav className="footer-links" aria-label="Footer navigation">{[...links,['Contact','/contact']].map(([label,url])=><a href={url} key={url}>{label}</a>)}</nav><div><span className="eyebrow">BASED IN</span><p>Surat, Gujarat, India<br/>Working with businesses everywhere.</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} AsterSync</span><a href="/privacy">Privacy policy</a></div></div></footer>}
