"use client";
import {useState,useRef,useEffect} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Asterisk,ArrowRight,Check,Play,RotateCcw,FileInput,Tags,UserRoundCheck,ListChecks} from 'lucide-react';
const orders=[{id:'ORD-1041',name:'Riverbend Textiles',value:184500,status:'In production',attention:false,due:'28 Sep'},{id:'ORD-1042',name:'Cotton & Co.',value:126000,status:'Ready to ship',attention:false,due:'26 Sep'},{id:'ORD-1043',name:'Loomline Studio',value:95000,status:'Awaiting approval',attention:true,due:'27 Sep'},{id:'ORD-1044',name:'Weave House',value:218000,status:'In production',attention:false,due:'30 Sep'},{id:'ORD-1045',name:'Threadworks',value:76000,status:'Payment pending',attention:true,due:'29 Sep'},{id:'ORD-1046',name:'Northfield Fabrics',value:143000,status:'Ready to ship',attention:false,due:'26 Sep'}];
const currency=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
export function OrderDemo(){const [filter,setFilter]=useState('all');const list=filter==='all'?orders:orders.filter(o=>o.attention);return <div className="order-demo"><div className="demo-app-top"><strong><Asterisk size={20}/> Order overview</strong><span className="demo-badge">FICTIONAL DATA</span></div><div className="demo-stat-grid"><div><span>Total order value</span><strong>{currency(orders.reduce((s,o)=>s+o.value,0))}</strong><small>Across 6 sample orders</small></div><div><span>Ready to ship</span><strong>02</strong><small>Next dispatch: 26 September</small></div><div><span>Needs attention</span><strong>02</strong><small>Approval and payment follow-up</small></div></div><Tabs value={filter} onValueChange={setFilter}><TabsList className="order-tabs"><TabsTrigger value="all">All orders (6)</TabsTrigger><TabsTrigger value="attention">Needs attention (2)</TabsTrigger></TabsList><TabsContent value={filter}><div className="order-table-scroll" role="region" aria-label="Sample orders table. Scroll horizontally to see all columns." tabIndex={0}><Table><TableHeader><TableRow><TableHead>Order / Customer</TableHead><TableHead>Value</TableHead><TableHead>Status</TableHead><TableHead>Delivery</TableHead></TableRow></TableHeader><TableBody>{list.map(o=><TableRow key={o.id}><TableCell><strong>{o.name}</strong><small>{o.id}</small></TableCell><TableCell>{currency(o.value)}</TableCell><TableCell><span className={'status-pill '+(o.attention?'attention':'')}>{o.status}</span></TableCell><TableCell>{o.due}</TableCell></TableRow>)}</TableBody></Table></div><p className="table-summary" aria-live="polite">Showing {list.length} of 6 sample orders · September 2026</p></TabsContent></Tabs></div>}
const stages=[{Icon:FileInput,title:'Capture the enquiry',copy:'A sample request for an order dashboard arrives from the website.'},{Icon:Tags,title:'Organise the request',copy:'The request is categorised as Data & reporting.'},{Icon:UserRoundCheck,title:'Assign the next step',copy:'A discovery conversation is assigned to the project team.'},{Icon:ListChecks,title:'Prepare the follow-up',copy:'A task is created with the project context ready to review.'}];
export function WorkflowDemo(){const [stage,setStage]=useState(0);const [running,setRunning]=useState(false);const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);async function run(){if(running)return;setRunning(true);setStage(0);for(let i=1;i<=4;i++){await new Promise(r=>setTimeout(r,550));if(!alive.current)return;setStage(i)}setRunning(false)}return <div className="workflow-demo"><div className="workflow-intro"><span className="demo-badge">INTERACTIVE SIMULATION</span><h3>One enquiry.<br/>Four connected steps.</h3><p>Follow a fictional project request from arrival to an organised follow-up.</p><button className="button" disabled={running} onClick={run}>{running?'Running simulation…':stage===4?'Run again':'Run sample enquiry'}{stage===4?<RotateCcw size={17}/>:<Play size={17}/>}</button><p className="subtle-note">This demo does not send messages or save enquiries.</p><p className="simulation-status" aria-live="polite">{stage===4?'Complete — the sample enquiry is ready for follow-up.':stage===0?'Ready when you are.':`Step ${stage} of 4 complete.`}</p></div><ol className="simulation-steps">{stages.map(({Icon,title,copy},i)=><li key={title} className={stage>i?'done':''}><span className="simulation-icon">{stage>i?<Check size={20}/>:<Icon size={20}/>}</span><div><span className="simulation-number">STEP 0{i+1}</span><h4>{title}</h4><p>{copy}</p></div><span className="simulation-check">{stage>i?<Check size={17}/>:<ArrowRight size={17}/>}</span></li>)}</ol></div>}
